str – FLOw
str Interface
3 statements
Source File
public interface str
Convert number (real and integer) to string (number to string type casting).
Calls
Called By
Module Procedures
strf_R8P str_R8P strf_R4P str_R4P strf_I8P str_I8P strf_I4P str_I4P strf_I2P str_I2P strf_I1P str_I1P str_bol str_a_R8P str_a_R4P str_a_I8P str_a_I4P str_a_I2P str_a_I1P
Module Procedures
private elemental function strf_R8P(fm, n) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
real(kind=R8P), intent(in) :: n
Real to be converted.
Return Value character(len=DR8P)
Returned string containing input number.
private elemental function str_R8P(n, no_sign, compact) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
Real to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=DR8P)
Returned string containing input number.
private elemental function strf_R4P(fm, n) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
real(kind=R4P), intent(in) :: n
Real to be converted.
Return Value character(len=DR4P)
Returned string containing input number.
private elemental function str_R4P(n, no_sign, compact) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n
Real to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=DR4P)
Returned string containing input number.
private elemental function strf_I8P(fm, n) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I8P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI8P)
Returned string containing input number.
private elemental function str_I8P(n, no_sign) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI8P)
Returned string containing input number plus padding zeros.
private elemental function strf_I4P(fm, n) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I4P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI4P)
Returned string containing input number.
private elemental function str_I4P(n, no_sign) result(str)
Converting integer to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI4P)
Returned string containing input number plus padding zeros.
private elemental function strf_I2P(fm, n) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I2P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI2P)
Returned string containing input number.
private elemental function str_I2P(n, no_sign) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI2P)
Returned string containing input number plus padding zeros.
private elemental function strf_I1P(fm, n) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I1P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI1P)
Returned string containing input number.
private elemental function str_I1P(n, no_sign) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI1P)
Returned string containing input number plus padding zeros.
private elemental function str_bol(n) result(str)
Convert logical to string.
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: n
Logical to be converted.
Return Value character(len=1)
Returned string containing input number plus padding zeros.
private pure function str_a_R8P(n, no_sign, separator, delimiters, compact) result(str)
Convert real array to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_R4P(n, no_sign, separator, delimiters, compact) result(str)
Convert real array to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_I8P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_I4P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_I2P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_I1P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
All Procedures
add add add array array array array_scalar array_vectorial assign_field assign_field assign_field assign_field_scalar assign_field_vectorial assign_real assign_real assign_real assign_real_scalar assign_real_vectorial assign_ScalI1P assign_ScalI2P assign_ScalI4P assign_ScalI8P assign_ScalR16P assign_ScalR4P assign_ScalR8P assign_self bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string compatible compute_derivate compute_fluxes compute_fluxes_from_primitive conservative_compressible conservative_compressible_instance conservative_compressible_pointer conservative_to_primitive_compressible cp crossproduct ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P cv delta density description description description description description_scalar description_vectorial destroy destroy destroy digit digit_I1 digit_I2 digit_I4 digit_I8 div div div div_integer div_integer div_integer div_real div_real div_real dotproduct energy energy eos_assign_eos eos_compressible eos_compressible_instance eq eq eq eq_scalar eq_vectorial eta face_normal3 face_normal3_self face_normal4 face_normal4_self g gm1 gp1 I1P_eq_self I1P_great_eq_self I1P_great_self I1P_low_eq_self I1P_low_self I1P_not_eq_self I2P_eq_self I2P_great_eq_self I2P_great_self I2P_low_eq_self I2P_low_self I2P_not_eq_self I4P_eq_self I4P_great_eq_self I4P_great_self I4P_low_eq_self I4P_low_self I4P_not_eq_self I8P_eq_self I8P_great_eq_self I8P_great_self I8P_low_eq_self I8P_low_self I8P_not_eq_self init_vector_self initialize initialize initialize integer_mul integer_mul integer_mul integer_mul_scalar integer_mul_vectorial internal_energy iolen_vector_self left_eigenvectors load_vector_self momentum momentum mul mul mul mul_integer mul_integer mul_integer mul_real mul_real mul_real negative negative negative negative_scalar negative_self negative_vectorial normalize normalize normalize normalize normalize_self normalized_self normL2 normL2_self not_eq not_eq not_eq not_eq_scalar not_eq_vectorial orthogonal parallel penf_init penf_print positive positive positive positive_scalar positive_self positive_vectorial pow_integer pow_integer pow_integer pow_real pow_real pow_real pressure pressure primitive_compressible primitive_compressible_instance primitive_compressible_multispecie primitive_compressible_multispecie_instance primitive_compressible_pointer primitive_to_conservative_compressible print_error print_error print_error print_error print_error print_error print_vector_self R R16P_eq_self R16P_great_eq_self R16P_great_self R16P_low_eq_self R16P_low_self R16P_not_eq_self R4P_eq_self R4P_great_eq_self R4P_great_self R4P_low_eq_self R4P_low_self R4P_not_eq_self R8P_eq_self R8P_great_eq_self R8P_great_self R8P_low_eq_self R8P_low_self R8P_not_eq_self real_mul real_mul real_mul real_mul_scalar real_mul_vectorial right_eigenvectors save_vector_self scalar_add_scalar scalar_div_integer scalar_div_real scalar_div_scalar scalar_mul_integer scalar_mul_object scalar_mul_real scalar_pow_integer scalar_pow_real scalar_sub_scalar ScalI1P_mul_self ScalI1P_sub_self ScalI1P_sum_self ScalI2P_mul_self ScalI2P_sub_self ScalI2P_sum_self ScalI4P_mul_self ScalI4P_sub_self ScalI4P_sum_self ScalI8P_mul_self ScalI8P_sub_self ScalI8P_sum_self ScalR16P_mul_self ScalR16P_sub_self ScalR16P_sum_self ScalR4P_mul_self ScalR4P_sub_self ScalR4P_sum_self ScalR8P_mul_self ScalR8P_sub_self ScalR8P_sum_self self_div_ScalI1P self_div_ScalI2P self_div_ScalI4P self_div_ScalI8P self_div_ScalR16P self_div_ScalR4P self_div_ScalR8P self_div_self self_eq_I1P self_eq_I2P self_eq_I4P self_eq_I8P self_eq_R16P self_eq_R4P self_eq_R8P self_eq_self self_great_eq_I1P self_great_eq_I2P self_great_eq_I4P self_great_eq_I8P self_great_eq_R16P self_great_eq_R4P self_great_eq_R8P self_great_eq_self self_great_I1P self_great_I2P self_great_I4P self_great_I8P self_great_R16P self_great_R4P self_great_R8P self_great_self self_low_eq_I1P self_low_eq_I2P self_low_eq_I4P self_low_eq_I8P self_low_eq_R16P self_low_eq_R4P self_low_eq_R8P self_low_eq_self self_low_I1P self_low_I2P self_low_I4P self_low_I8P self_low_R16P self_low_R4P self_low_R8P self_low_self self_mul_ScalI1P self_mul_ScalI2P self_mul_ScalI4P self_mul_ScalI8P self_mul_ScalR16P self_mul_ScalR4P self_mul_ScalR8P self_mul_self self_not_eq_I1P self_not_eq_I2P self_not_eq_I4P self_not_eq_I8P self_not_eq_R16P self_not_eq_R4P self_not_eq_R8P self_not_eq_self self_sub_ScalI1P self_sub_ScalI2P self_sub_ScalI4P self_sub_ScalI8P self_sub_ScalR16P self_sub_ScalR4P self_sub_ScalR8P self_sub_self self_sum_ScalI1P self_sum_ScalI2P self_sum_ScalI4P self_sum_ScalI8P self_sum_ScalR16P self_sum_ScalR4P self_sum_ScalR8P self_sum_self set_vector_self speed_of_sound sq_norm sq_norm_self str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P sub sub sub temperature total_entalpy vectorial_add_vectorial vectorial_div_integer vectorial_div_object vectorial_div_real vectorial_mul_integer vectorial_mul_object vectorial_mul_real vectorial_pow_integer vectorial_pow_real vectorial_sub_vectorial velocity
Call graph
str calls strf_i2p, str_a_i2p, strf_r8p, str_bol, str_i8p, strf_r4p, str_r4p, str_a_i8p, str_i2p, str_a_i1p, str_a_r8p, str_i1p, strf_i8p, str_i4p, str_r8p, strf_i1p, str_a_r4p, strf_i4p, str_a_i4p
str_a_i2p calls str_i2p
str_r4p calls compact_real_string
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_r8p calls compact_real_string
str_a_r4p calls str_r4p
str_a_i4p calls str_i4p
description calls str
bctor_r4p calls str
bctoi_i1p calls str
description_vectorial calls str
bctor_r16p calls str
description_scalar calls str
bctoi_i4p calls str
bctor_r8p calls str
bctoi_i2p calls str
bctoi_i8p calls str
print_vector_self calls str
bcton calls bctor_r4p, bctoi_i1p, bctoi_i4p, bctor_r8p, bctoi_i2p, bctoi_i8p